//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFAInventorySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_report
    {
        public int r_id { get; set; }
        public string r_name { get; set; }
        public string r_desc { get; set; }
        public Nullable<System.DateTime> r_date { get; set; }
        public Nullable<double> r_profits { get; set; }
        public Nullable<double> r_capitals { get; set; }
        public Nullable<int> r_vmID { get; set; }
        public Nullable<int> r_sid { get; set; }
    
        public virtual tb_vendingmachine tb_vendingmachine { get; set; }
        public virtual tb_stock tb_stock { get; set; }
    }
}
