//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFAInventorySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_vendingmachine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_vendingmachine()
        {
            this.tb_stockhistory = new HashSet<tb_stockhistory>();
        }
    
        public int v_id { get; set; }
        public string v_location { get; set; }
        public Nullable<double> v_cashInSlot { get; set; }
        public Nullable<double> v_profit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_stockhistory> tb_stockhistory { get; set; }
    }
}
